doc/changes/20200814Munch-3, include/hyper.deal/matrix_free/fe_evaluation_cell.h, include/hyper.deal/numerics/vector_tools.h, include/hyper.deal/operators/advection/advection_operation.h
This is still a sin from the early stages of hyper.deal and my first attempts to understand deal.II.
=> Rename FEEvaluation::distribute_local_to_global() to set_dof_values()

include/hyper.deal/matrix_free/matrix_free.cc, include/hyper.deal/matrix_free/matrix_free.h
=> Add MatrixFree::get_dof_info() and ::get_face_info()

include/hyper.deal/matrix_free/read_write_operation.h
... noticed while working on #24.
=> Fix some warnings

include/hyper.deal/matrix_free/evaluation_kernels.h, include/hyper.deal/operators/advection/advection_operation.h
Use `UnivariateShapeData::quadrature_data_on_face` (see also https://github.com/dealii/dealii/pull/10870).
FYI @kronbichler
=> Use new deal.II functions (II)

include/hyper.deal/matrix_free/evaluation_kernels.h, include/hyper.deal/operators/advection/advection_operation.h
make the code similar to https://github.com/dealii/dealii/blob/b6c01a60113e686d64a295e586bd4f49d1d33c6c/include/deal.II/matrix_free/tensor_product_kernels.h#L398-L532
In the next step, I will try to move the implementation in deal.II.
FYI @kronbichler
=> Restructure FEFaceNormalEvaluation

examples/advection/cases/torus_hyperball.h, examples/advection/include/parameters.h, examples/vlasov_poisson/cases/torus_hyperball.h, examples/vlasov_poisson/include/parameters.h, include/hyper.deal/grid/grid_generator.h, source/grid/grid_generator.cc, source/grid/grid_generator.inst.in
**Note:** Not working yet properly. Waiting for https://github.com/dealii/dealii/pull/10971. I will add a test once that PR is merged.
=> Add torus simulation cases

examples/advection/include/application.h, examples/advection/include/parameters.h, examples/vlasov_poisson/include/application.h, examples/vlasov_poisson/include/parameters.h, include/hyper.deal/base/config.h, include/hyper.deal/base/timers.h, include/hyper.deal/matrix_free/matrix_free.h, include/hyper.deal/matrix_free/matrix_free.templates.h, include/hyper.deal/matrix_free/vector_partitioner.h, tests/tests_mf.h
- work on timers
- remove references to `MPI_Comm` since it cause problems on SKX
- some preparations related to #18
=> Different minor modifications

.github/workflows/tests.yml
I tried to adjust the tests according to https://www.petefreitag.com/item/903.cfm but failed. At least now the commands run in the docker image are separate lines...
=> Simplify test

examples/advection/cases/torus_hyperball.h, examples/vlasov_poisson/cases/torus_hyperball.h, source/grid/grid_generator.cc, tests/poisson/poisson_03.cc, tests/poisson/poisson_03.output, tests/poisson/poisson_03.with_dummy=off.output
=> Remove TransfiniteInterpolationManifold from torus

examples/vlasov_poisson/include/application.h, examples/vlasov_poisson/include/derivative_container.h
Requires https://github.com/dealii/dealii/pull/11147.
=> VP: Fix ECL for non-periodic BCs

.github/workflows/nightly.yml, README.MD
The tests are run in release mode once a day at 12 pm UTC.
=> Add nightly tests

tests/poisson/poisson_03.output
... related to https://github.com/dealii/dealii/pull/12423.
FYI @kronbichler
=> Update test output

include/hyper.deal/operators/advection/advection_operation.h, performance/operators_advection_02.likwid.cc
due to https://github.com/dealii/dealii/pull/12625
=> Update to new deal.II interface (hessian)

include/hyper.deal/base/timers.h, include/hyper.deal/matrix_free/vector_partitioner.h, source/base/mpi.cc
related to https://github.com/dealii/dealii/pull/13367
=> Update deal.II: internal::mpi_type_id() -> mpi_type_id()

tests/poisson/poisson_01.cc, tests/poisson/poisson_02.cc, tests/poisson/poisson_03.cc
related to https://github.com/dealii/dealii/pull/13422
=> Include grid_tools.h

include/hyper.deal/matrix_free/evaluation_kernels.h, include/hyper.deal/matrix_free/shape_info.h, include/hyper.deal/operators/advection/advection_operation.h, performance/operators_advection_02.likwid.cc, tests/matrix_free/fefaceevalutation_02.cc, tests/matrix_free/fefaceevalutation_02.mpirun=1.output
Alternative to #100.
~For now just FCL. For ECL, we need to adjust: 
https://github.com/hyperdeal/hyperdeal/blob/5fe43a4e6b88897d7b8f33fde5de4af15e92c751/include/hyper.deal/operators/advection/advection_operation.h#L427~
@yl3dy Could you try this PR out?
@kronbichler Do you agree with the direction of the PRs?
=> Reorient faces according to deal.II (FCL + ECL)

examples/vlasov_poisson/include/derivative_container.h
references https://github.com/hyperdeal/hyperdeal/issues/116
=> Use dealii::Utilities::pow()

CMakeLists.txt
references https://github.com/hyperdeal/hyperdeal/issues/115
=> Set CMAKE_CXX_STANDARD 17

CMakeLists.txt
As suggested by https://github.com/hyperdeal/hyperdeal/issues/115#issuecomment-1629921066.
=> Add additional CMake configurations

include/hyper.deal/numerics/vector_tools.h, include/hyper.deal/operators/advection/advection_operation.h, tests/matrix_free/fefaceevalutation_02.cc
=> Fix compilation
